#!/bin/sh
fuser -k -n tcp 9999                                                                           #Kills process using port 9999
#kill $(lsof -i | grep "9999" | awk '{print $2}') > /dev/null 2> &1 
#kill $(lsof -i | grep "8080" | awk '{print $2}') > /dev/null 2> &1
/etc/init.d/networking restart
python /home/appusr_swilch/swilch/swilch_application_000.000.003/example_script.py
date >> /home/appusr_swilch/swilch/swilch_application_000.000.003/log.txt
sleep 5s


