#!/bin/sh 
sleep 5
python "/home/appusr_swilch/swilch/swilch_application_000.000.003/example_script.py"
sleep 5
python "/home/appusr_swilch/swilch/swilch_application_000.000.003/Custom_Monitor.py"



