#!/bin/sh
echo 0x85 > /home/appusr_swilch/swilch/swilch_application_000.000.003/USB_Code  #Assume specified device is not connected by default
for a in /sys/bus/usb/devices/* ; do
        if [  `ls $a | grep "idProduct"` ] &&  [  `ls $a | grep "idVendor"` ]   ; then      # To search through folders only containing connected devices

           if [ `cat $a/idVendor`  =  $1  ] && [ `cat $a/idProduct` = $2 ]; then            # To identify the folder with the required credentials
            echo 0 > $a/authorized ;
            sleep 0.5s
            echo 1 > $a/authorized ;
            echo 0x86 > /home/appusr_swilch/swilch/swilch_application_000.000.003/USB_Code  # If device is found , reset it

           fi
        fi 
     done ;

exit 0 ;
  

